---
deployment:
  tasks:
    - export PUBLICPATH=/home/u1575760/public_html/prototype-intern-pens/
    - export APPPATH=/home/u1575760/prototype-intern-pens/

    # Copy the contents of the public directory (not the directory itself)
    - /bin/cp -R public/* $PUBLICPATH

    # Synchronize the rest of the application excluding the public directory
    - /bin/rsync -avz --exclude public/ . $APPPATH
