---
deployment:
  tasks:
    - export PUBLICPATH=/home/u1575760/public_html/prototype-intern-pens/
    - export APPPATH=/home/u1575760/prototype-intern-pens/

    - /bin/cp -R public $PUBLICPATH
    - /bin/rsync -avz --exclude public/ . $APPPATH
