---
deployment:
  tasks:
    - export PUBLICPATH=/home/u1575760/public_html/prototype-intern-mitral/
    - export APPPATH=/home/u1575760/prototype-intern-mitral/

    - /bin/mv public/* $PUBLICPATH
    - /bin/mv $(ls -A | grep -v public) $APPPATH
